module.exports = dummyData = [
  {
    id: 1,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
  {
    id: 2,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
  {
    id: 3,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
  {
    id: 4,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
  {
    id: 5,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
  {
    id: 6,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
  {
    id: 7,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
  {
    id: 8,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
  {
    id: 9,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
  {
    id: 10,
    user_id: 5,
    word_eng: 'camera',
    word_kor: '카메라',
    distinguish: 99,
  },
];
